<a href="https://colab.research.google.com/github/fralfaro/MAT281/blob/main/docs/labs/lab_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# MAT281 - Laboratorio N°03



**Objetivo**: Aplicar técnicas avanzadas de manipulación y análisis de datos con pandas sobre un conjunto real de datos de contenido de Netflix, reforzando buenas prácticas y métodos eficientes sin recurrir a `groupby`, `merge`, `pivot`, ni `join`.



**Dataset**:

Trabajaremos con el archivo `netflix_titles.csv`, que contiene información sobre los títulos disponibles en la plataforma Netflix hasta el año 2021.

| Variable       | Clase     | Descripción                                                                 |
|----------------|-----------|------------------------------------------------------------------------------|
| show_id        | caracter  | Identificador único del título en el catálogo de Netflix.                   |
| type           | caracter  | Tipo de contenido: 'Movie' o 'TV Show'.                                     |
| title          | caracter  | Título del contenido.                                                       |
| director       | caracter  | Nombre del director (puede ser nulo).                                       |
| cast           | caracter  | Lista de actores principales (puede ser nulo).                              |
| country        | caracter  | País o países donde se produjo el contenido.                                |
| date_added     | fecha     | Fecha en la que el título fue agregado al catálogo de Netflix.              |
| release_year   | entero    | Año de lanzamiento original del título.                                     |
| rating         | caracter  | Clasificación por edad (por ejemplo: 'PG-13', 'TV-MA').                      |
| duration       | caracter  | Duración del contenido (minutos o número de temporadas para series).        |
| listed_in      | caracter  | Categorías o géneros en los que está clasificado el contenido.              |
| description    | caracter  | Breve sinopsis del contenido.                                               |

In [24]:
import pandas as pd

# Cargar datos
df = pd.read_csv('https://raw.githubusercontent.com/fralfaro/MAT281/main/docs/labs/data/netflix_titles.csv')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...


### Parte 1: Limpieza y preparación

1. Revisar y describir el dataset:

   * ¿Cuántas filas y columnas tiene?
   * ¿Qué tipos de datos hay?
   * ¿Cuántos valores nulos hay por columna?

2. Transformar la columna `date_added` a tipo fecha.

3. Crear columnas auxiliares con `assign`:

   * Año (`year_added`)
   * Mes (`month_added`)

In [5]:
#FIXME
df.shape

(8807, 12)

In [6]:
df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [7]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [25]:
import datetime

df['date_added'] = pd.to_datetime(df['date_added'],errors='coerce') #errors='coerce' se usa para convertir valores nulos a NaT (Not a Time)
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [26]:
df = df.assign(year=df['date_added'].dt.year,
               month=df['date_added'].dt.month)
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year,month
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021.0,9.0
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,9.0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021.0,9.0
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021.0,9.0
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021.0,9.0

## Parte 2: Técnicas avanzadas de pandas

4. Utilizar `.loc` para seleccionar películas (`type == 'Movie'`) que fueron agregadas después del año 2018.

5. Utilizar `str.contains()` y `str.extract()`:

   * Filtrar títulos que contienen la palabra 'love' (sin distinguir mayúsculas/minúsculas).
   * Extraer la duración en minutos para las películas desde la columna `duration`.

6. Aplicar `explode()` sobre la columna `listed_in` para obtener una fila por cada género.

7. Obtener un top 10 de géneros más frecuentes utilizando `value_counts()`.

8. Aplicar `where()` y `mask()` para marcar las películas de más de 120 minutos como contenido largo en una nueva columna.

9. Utilizar `.loc` para filtrar películas que cumplen con:

   * Más de 100 minutos de duración.
   * Rating igual a `'R'`.
   * País igual a `'United States'`.

10. Utilizar `.style` para formatear visualmente el top 10 de películas más largas.

In [44]:
#FIXME
df_new = df.loc[(df['type'] == 'Movie') & (df['year']>2018)] #Considerando que "despúes del año 2018" no incluye a este
df_new = df_new[df_new['title'].str.contains('love', case=False)]
df_new['duration_min'] = df_new['duration'].str.extract(r'(\d+)')
df_new['listed_in'] = df_new['listed_in'].str.split(', ')
df_new = df_new.explode('listed_in')
top10 = df_new['listed_in'].value_counts().head(10)
print(top10)
df_new['duration_min'] = pd.to_numeric(df_new['duration_min'])
over120 = df_new['duration_min'] > 120
df_new['longitud'] = 'Normal'
df_new['longitud'] = df_new['longitud'].mask(over120, 'Largo')
df_new = df_new.loc[(df_new['duration_min'] >=100) & (df_new['rating']=='R') & (df_new['country']=='United States')]
df_new.head()

listed_in
International Movies    56
Romantic Movies         52
Dramas                  48
Comedies                35
Independent Movies      10
Music & Musicals         6
Thrillers                5
Documentaries            5
Sci-Fi & Fantasy         3
Action & Adventure       3
Name: count, dtype: int64

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year,month,duration_min,longitud
615,s616,Movie,Why Do Fools Fall in Love,Gregory Nava,"Halle Berry, Vivica A. Fox, Larenz Tate, Lela ...",United States,2021-07-01,1998,R,116 min,Dramas,"In this rock 'n' roll comedy-drama, three wome...",2021.0,7.0,116,Normal
615,s616,Movie,Why Do Fools Fall in Love,Gregory Nava,"Halle Berry, Vivica A. Fox, Larenz Tate, Lela ...",United States,2021-07-01,1998,R,116 min,Music & Musicals,"In this rock 'n' roll comedy-drama, three wome...",2021.0,7.0,116,Normal
615,s616,Movie,Why Do Fools Fall in Love,Gregory Nava,"Halle Berry, Vivica A. Fox, Larenz Tate, Lela ...",United States,2021-07-01,1998,R,116 min,Romantic Movies,"In this rock 'n' roll comedy-drama, three wome...",2021.0,7.0,116,Normal
798,s799,Movie,Love Jones,Theodore Witcher,"Larenz Tate, Nia Long, Isaiah Washington, Lisa...",United States,2021-06-02,1997,R,109 min,Comedies,A poet and a photographer take a chance on rom...,2021.0,6.0,109,Normal
798,s799,Movie,Love Jones,Theodore Witcher,"Larenz Tate, Nia Long, Isaiah Washington, Lisa...",United States,2021-06-02,1997,R,109 min,Dramas,A poet and a photographer take a chance on rom...,2021.0,6.0,109,Normal

In [45]:
top10df = df_new[['title', 'release_year', 'duration_min']]
top10df = top10df.reset_index(drop=True)
top10df.style.background_gradient(subset=['duration_min'], cmap='viridis')

In [46]:
df_new = df.loc[(df['type'] == 'Movie') & (df['year']>2018)] #Considerando que "despúes del año 2018" no incluye a este
df_new = df_new[df_new['title'].str.contains('love', case=False)]
df_new['duration_min'] = df_new['duration'].str.extract(r'(\d+)')
df_new['listed_in'] = df_new['listed_in'].str.split(', ')
df_new = df_new.explode('listed_in')
top10 = df_new['listed_in'].value_counts().head(10)
print(top10)
df_new['duration_min'] = pd.to_numeric(df_new['duration_min'])
over120 = df_new['duration_min'] > 120
df_new['longitud'] = 'Largo'
df_new['longitud'] = df_new['longitud'].where(over120, 'Normal')
df_new = df_new.loc[(df_new['duration_min'] >=100) & (df_new['rating']=='R') & (df_new['country']=='United States')]
df_new.head()

listed_in
International Movies    56
Romantic Movies         52
Dramas                  48
Comedies                35
Independent Movies      10
Music & Musicals         6
Thrillers                5
Documentaries            5
Sci-Fi & Fantasy         3
Action & Adventure       3
Name: count, dtype: int64

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year,month,duration_min,longitud
615,s616,Movie,Why Do Fools Fall in Love,Gregory Nava,"Halle Berry, Vivica A. Fox, Larenz Tate, Lela ...",United States,2021-07-01,1998,R,116 min,Dramas,"In this rock 'n' roll comedy-drama, three wome...",2021.0,7.0,116,Normal
615,s616,Movie,Why Do Fools Fall in Love,Gregory Nava,"Halle Berry, Vivica A. Fox, Larenz Tate, Lela ...",United States,2021-07-01,1998,R,116 min,Music & Musicals,"In this rock 'n' roll comedy-drama, three wome...",2021.0,7.0,116,Normal
615,s616,Movie,Why Do Fools Fall in Love,Gregory Nava,"Halle Berry, Vivica A. Fox, Larenz Tate, Lela ...",United States,2021-07-01,1998,R,116 min,Romantic Movies,"In this rock 'n' roll comedy-drama, three wome...",2021.0,7.0,116,Normal
798,s799,Movie,Love Jones,Theodore Witcher,"Larenz Tate, Nia Long, Isaiah Washington, Lisa...",United States,2021-06-02,1997,R,109 min,Comedies,A poet and a photographer take a chance on rom...,2021.0,6.0,109,Normal
798,s799,Movie,Love Jones,Theodore Witcher,"Larenz Tate, Nia Long, Isaiah Washington, Lisa...",United States,2021-06-02,1997,R,109 min,Dramas,A poet and a photographer take a chance on rom...,2021.0,6.0,109,Normal

In [ ]:
top10df = df_new[['title', 'release_year', 'duration_min']]
top10df = top10df.reset_index(drop=True)
top10df.style.background_gradient(subset=['duration_min'], cmap='viridis')



### Pregunta Desafío

11. ¿Cuáles son las combinaciones más frecuentes de género y rating en el dataset?
    (Sugerencia: utilizar `value_counts` con `subset=["genre", "rating"]` después de aplicar `explode()`).



### Bonus: Análisis de duplicados y limpieza

12. ¿Existen películas con el mismo nombre (`title`) pero con distinto año de lanzamiento (`release_year`)?
13. ¿Cuántos títulos únicos hay en total en la columna `title`?

In [ ]:
#FIXME